      SUBROUTINE LSOUT(ILOC,ITEST,XMIN,FMIN,GMIN,XW,FW,GW,U,A,
     *     B,TOL,EPS,SCXBD,XLAMDA)
c      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION XMIN,FMIN,GMIN,XW,FW,GW,U,A,B,
     *     TOL,EPS,SCXBD,XLAMDA
      INTEGER iloc,itest
C
C ERROR PRINTOUTS FOR GETPTC
C
      DOUBLE PRECISION YA,YB,YBND,YW,YU
      YU = XMIN + U
      YA = A + XMIN
      YB = B + XMIN
      YW = XW + XMIN
      YBND = SCXBD + XMIN
      WRITE(*,800)
      WRITE(*,810) TOL,EPS
      WRITE(*,820) YA,YB
      WRITE(*,830) YBND
      WRITE(*,840) YW,FW,GW
      WRITE(*,850) XMIN,FMIN,GMIN
      WRITE(*,860) YU
      WRITE(*,870) ILOC,ITEST
      RETURN
800   FORMAT(///' OUTPUT FROM LINEAR SEARCH')
810   FORMAT('  TOL AND EPS'/2D25.14)
820   FORMAT('  CURRENT UPPER AND LOWER BOUNDS'/2D25.14)
830   FORMAT('  STRICT UPPER BOUND'/D25.14)
840   FORMAT('  XW, FW, GW'/3D25.14)
850   FORMAT('  XMIN, FMIN, GMIN'/3D25.14)
860   FORMAT('  NEW ESTIMATE'/2D25.14)
870   FORMAT('  ILOC AND ITEST'/2I3)
      END
