      DOUBLE PRECISION FUNCTION MCHPR1()
c      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C RETURNS THE VALUE OF EPSMCH, WHERE EPSMCH IS THE SMALLEST POSSIBLE
C REAL NUMBER SUCH THAT 1.0 + EPSMCH .GT. 1.0
C
C FOR HP 720
C
      MCHPR1 = 2.D-16
      RETURN
      END
