      SUBROUTINE NDIA3(N,E,V,GV,R,VGV,MODET)
c      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      integer n,modet,i
      DOUBLE PRECISION E(N),V(N),GV(N),R(N),VGV,VR,DDOT
C
C UPDATE THE PRECONDITIOING MATRIX BASED ON A DIAGONAL VERSION
C OF THE BFGS QUASI-NEWTON UPDATE.
C
      VR = DDOT(N,V,1,R,1)
      DO 10 I = 1,N
         E(I) = E(I) - R(I)*R(I)/VR + GV(I)*GV(I)/VGV
         IF (E(I) .GT. 1.D-6) GO TO 10
         IF (MODET .GT. -2) WRITE(*,800) E(I)
         E(I) = 1.D0
10    CONTINUE
      RETURN
800   FORMAT(' *** EMAT NEGATIVE:  ',1PD16.8)
      END
